#ifndef WATER_LEVEL_INTERFACE_DATA_TYPES_H_
#define WATER_LEVEL_INTERFACE_DATA_TYPES_H_

#include <vector>

#define	SUPPLY_SOURCE_TANK 0x00
#define	SUPPLY_SOURCE_PIPE 0x01
#define	SUPPLY_SOURCE_NOT_SUPPORTED 0xFF

#endif /* WATER_LEVEL_INTERFACE_DATA_TYPES_H_ */
